/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#711419",
              "inverse-on-surface": "#ebf3eb",
              "error": "#ba1a1a",
              "surface-container-high": "#e3eae3",
              "surface-bright": "#f4fbf4",
              "surface-container-low": "#eef6ee",
              "secondary-fixed-dim": "#c0c7d6",
              "on-error": "#ffffff",
              "outline-variant": "#bbcabf",
              "on-primary-fixed-variant": "#005236",
              "inverse-primary": "#4edea3",
              "primary-fixed-dim": "#4edea3",
              "on-tertiary-fixed": "#410005",
              "on-surface-variant": "#3c4a42",
              "background": "#f4fbf4",
              "primary": "#006c49",
              "tertiary-fixed": "#ffdad7",
              "secondary-fixed": "#dce2f3",
              "primary-container": "#10b981",
              "on-primary": "#ffffff",
              "on-secondary": "#ffffff",
              "on-primary-fixed": "#002113",
              "surface-variant": "#dde4dd",
              "on-secondary-fixed-variant": "#404754",
              "on-error-container": "#93000a",
              "on-primary-container": "#00422b",
              "surface-container-highest": "#dde4dd",
              "tertiary-container": "#fc7c78",
              "on-tertiary": "#ffffff",
              "tertiary-fixed-dim": "#ffb3af",
              "surface-tint": "#006c49",
              "on-surface": "#161d19",
              "secondary-container": "#dce2f3",
              "secondary": "#585f6c",
              "primary-fixed": "#6ffbbe",
              "outline": "#6c7a71",
              "surface-container": "#e8f0e9",
              "surface-container-lowest": "#ffffff",
              "on-secondary-container": "#5e6572",
              "surface-dim": "#d4dcd5",
              "surface": "#f4fbf4",
              "on-secondary-fixed": "#151c27",
              "on-tertiary-fixed-variant": "#842225",
              "on-background": "#161d19",
              "tertiary": "#a43a3a",
              "inverse-surface": "#2b322d",
              "error-container": "#ffdad6"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "sm": "12px",
              "base": "4px",
              "xs": "8px",
              "xl": "32px",
              "lg": "24px",
              "md": "16px",
              "container-margin": "40px",
              "gutter": "24px"
      },
      "fontFamily": {
              "body-lg": ["Inter", "sans-serif"],
              "helper-text": ["Inter", "sans-serif"],
              "label-caps": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "h2": ["Manrope", "sans-serif"],
              "display": ["Manrope", "sans-serif"],
              "h1": ["Manrope", "sans-serif"]
      },
      "fontSize": {
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "helper-text": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
              "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "h2": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h1": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
